pages:
  stage: deploy
  script:
  - mkdir -p .public/clasificacion .public/equipo
  - cp -r clasificacion/* .public/clasificacion
  - cp -r equipo/* .public/equipo
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - main