pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public/.public/src/clasificacion
    - public/.public/src/equipo
  only:
  - main